name: Moeez

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
name: devops app

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    # run all `run:` steps inside the FlaskWebProject1 folder where the app lives
    defaults:
      run:
        working-directory: FlaskWebProject1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: List Files
        run: echo "Moeez is great"
    branches: [ "main", "master" ]

name: Install Dependencies
      run: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt
       python -m pip install flake8
deploy:
    runs-on: ubuntu-latest
    needs: build



